version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine

  kafka:
    image: bitnami/kafka:latest

  zookeeper:
    image: bitnami/zookeeper:latest
    
  consul:
    image: consul

  mongoclient:
    image: mongoclient/mongoclient

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.2

  catalog_mongodb:
    image: mongo
  
  outboxdb:
    image: mongo
  
  catalog_mssqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  
  catalog_redisdb:
    image: redis:alpine
  
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: ../
      dockerfile: Src/Services/Catalog/Catalog.Api/Dockerfile

  basket_redisdb:
    image: redis:alpine

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: ../
      dockerfile: Src/Services/basket/Basket.Api/Dockerfile

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: ../
      dockerfile: Src/ApiGetways/OcelotApiGw/OcelotApiGw/Dockerfile

volumes:
  catalog_mongo_data:
  outbox_mongo_data:
  consul_data:
  elasticsearch_data:
  kafka_data:
