version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  catalog.mongodb:
    container_name: catalog.mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  catalog.mssqldb:
    container_name: catalog.mssqldb
    restart: always
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
  
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "MongoDbSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalog.mongodb
      - catalog.mssqldb
      - rabbitmq
    ports:
      - "8000:80"
